name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        spack-manifest-path:
          - .github/build-ci/manifests/gcc.spack.yaml.j2
          - .github/build-ci/manifests/intel.spack.yaml.j2
    uses: access-nri/build-ci/.github/workflows/ci-github-hosted.yml@v2
    with:
      spack-manifest-path: ${{ matrix.spack-manifest-path }}
      spack-config-ref: 2025.11.000  # Before build-ci@v2-breaking change to spack-config, don't go any further forward!
      spack-packages-ref: api-v2  # This branch contains the package defs compatible with spack >=1.0. May be incorporated into the main branch
      spack-ref: releases/v1.0
      allow-ssh-into-spack-install: false
      container-image-version: :rocky-v1.0-2025.09.000  # https://github.com/ACCESS-NRI/build-ci/pkgs/container/build-ci-upstream/501398004?tag=rocky-v1.0-2025.09.000
      spack-oci-buildcache-url: oci://ghcr.io/CABLE-LSM/build-ci-buildcache  # https://github.com/CABLE-LSM/CABLE/pkgs/container/build-ci-buildcache
    permissions:
      packages: write
